"""Constants used by the `timesync` extension."""

DEFAULT_SYNC_THRESHOLD = 0.1
DEFAULT_SOURCE_EXPIRY_THRESHOLD = 30 * 60
DEFAULT_OFFSET_LOG_THRESHOLD = 0.1

MIN_REFRESH_PERIOD = 1.0
MAX_REFRESH_PERIOD = 60.0
