#!/bin/bash

# TODO(ntamas): if $0 is a symlink, resolve where it points to
SCRIPT_PATH="$0"
if [ -L "${SCRIPT_PATH}" ]; then
  SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`
fi
SCRIPT_ROOT=`dirname "${SCRIPT_PATH}"`

pushd "${SCRIPT_ROOT}/.." >/dev/null
SKYBRUSH_ROOT=`pwd`
popd >/dev/null

PYARMOR_LICENSE="${SKYBRUSH_ROOT}/skybrushd.cml"

if [ ! -f "${PYARMOR_LICENSE}" ]; then
    echo "No license file found at ${PYARMOR_LICENSE}"
    echo ""
    echo "Please add your license file there before starting the server."
    exit 1
fi

export PYARMOR_LICENSE

chmod a+x "${SKYBRUSH_ROOT}/lib/skybrushd"
exec "${SKYBRUSH_ROOT}/lib/skybrushd" "$@"
