#!/bin/bash

set -e

SCRIPT_PATH="$0"

# If $0 is a symlink, resolve where it points to
if [ -L "${SCRIPT_PATH}" ]; then
  SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`
fi
SCRIPT_ROOT=`dirname "${SCRIPT_PATH}"`

# This script is expected to be in bin/ so resolve the parent folder
pushd "${SCRIPT_ROOT}/.." >/dev/null
SKYBRUSH_ROOT=`pwd`
popd >/dev/null

# Check whether the user has placed the license file appropriately
PYARMOR_LICENSE="${SKYBRUSH_ROOT}/skybrushd.cml"
if [ ! -f "${PYARMOR_LICENSE}" ]; then
  echo "No license file found at ${PYARMOR_LICENSE}"
  echo ""
  echo "Please add your license file there before starting the server."
  exit 1
fi
export PYARMOR_LICENSE

# Check if the user has specified an alternative configuration file; if not,
# use the default configuration file
DEFAULT_CONFIG="${SKYBRUSH_ROOT}/skybrush.jsonc"
for arg in "$@"; do
  if [ "x$arg" = "x-c" -o "x$arg" = "x--config" ]; then
    DEFAULT_CONFIG=""
  fi
done

# Start the server
chmod a+x "${SKYBRUSH_ROOT}/lib/skybrushd"
if [ "x${DEFAULT_CONFIG}" != x ]; then
  exec "${SKYBRUSH_ROOT}/lib/skybrushd" -c "$DEFAULT_CONFIG" "$@"
else
  exec "${SKYBRUSH_ROOT}/lib/skybrushd" "$@"
fi
